Reorder functions; switch from '[' tests to '[['

diff --git a/poptail b/poptail
--- a/poptail
+++ b/poptail
@@ -23,29 +23,15 @@ main () {
     parse_args "$@"
     check_infile
 
-    tail_cmd () { tail "${tail_flags[@]:+${tail_flags[@]}}" "$infile"; }
-
     set_lockfile
     (
         flock -x --timeout 10 9 || die_lock_error
-        if [ $dry_run_opt == 1 ]; then
+        if [[ $dry_run_opt == 1 ]]; then
             do_dry_run
         else
             do_poptail
         fi
     ) 9>"$lockfile"
-}
-
-check_infile () {
-    if [ ! -e "$infile" ]; then
-        die "cannot open '$infile' for reading: No such file or directory"
-    elif [ -d "$infile" ]; then
-        die "error reading '$infile': Is a directory"
-    elif [ ! -r "$infile" ]; then
-        die "cannot open '$infile' for reading: Permission denied"
-    elif [ ! -w "$infile" ]; then
-        die "cannot open '$infile' for writing: Permission denied"
-    fi
 }
 
 do_dry_run () {
@@ -55,38 +41,35 @@ do_dry_run () {
 }
 
 do_poptail () {
-    # If ifne is prensent then it can be used to stop the pipe in case an
-    # error happens in tail_cmd.
+    # If ifne is present then it can be used to stop the pipe in case an error
+    # happens in tail_cmd.
     hash ifne 2>/dev/null
-    if [ $? == 0 ]; then
+    if [[ $? == 0 ]]; then
         tail_cmd | ifne tee >(wc -c | xargs -I {} truncate "$infile" -s -{})
     else
         tail_cmd | tee >(wc -c | xargs -I {} truncate "$infile" -s -{})
     fi
 }
 
+tail_cmd () {
+    tail "${tail_flags[@]:+${tail_flags[@]}}" "$infile"
+}
+
+check_infile () {
+    if [[ ! -e "$infile" ]]; then
+        die "cannot open '$infile' for reading: No such file or directory"
+    elif [[ -d "$infile" ]]; then
+        die "error reading '$infile': Is a directory"
+    elif [[ ! -r "$infile" ]]; then
+        die "cannot open '$infile' for reading: Permission denied"
+    elif [[ ! -w "$infile" ]]; then
+        die "cannot open '$infile' for writing: Permission denied"
+    fi
+}
+
 set_lockfile () {
     local cannonical_fname=$(readlink -f "$infile")
     lockfile="$lockfile_path/LCK.poptail${cannonical_fname//\//-}"
-}
-
-die () {
-    echo "poptail: $1" >&2
-    exit 1
-}
-
-die_usage () {
-    echo "poptail: $1" >&2
-    usage_msg
-    exit 1
-}
-
-die_lock_error () {
-    die "Lock for poptail not acquired: $lockfile"
-}
-
-usage_msg () {
-    echo "Try 'poptail -h' for more information." >&2
 }
 
 parse_args () {
@@ -113,9 +96,28 @@ parse_args () {
         esac
     done
     shift $((OPTIND-1))
-    [ "$#" == 0 ] && die_usage "missing file argument"
-    [ "$#" -gt  1 ] && die_usage "too many arguments"
+    [[ "$#" == 0 ]] && die_usage "missing file argument"
+    [[ "$#" -gt  1 ]] && die_usage "too many arguments"
     infile=$1
+}
+
+die_lock_error () {
+    die "Lock for poptail not acquired: $lockfile"
+}
+
+die () {
+    echo "poptail: $1" >&2
+    exit 1
+}
+
+die_usage () {
+    echo "poptail: $1" >&2
+    usage_msg
+    exit 1
+}
+
+usage_msg () {
+    echo "Try 'poptail -h' for more information." >&2
 }
 
 show_help () {
